name: default

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  mssql-sdk:
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet_version: ["9.0", "10.0"]
        sql_version: [2025-latest, 2022-latest]

    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: login ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: setup docker
        uses: docker/setup-buildx-action@v3

      - name: extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/escd/dotnet-mssql-sdk
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: publish image
        id: publish
        uses: docker/build-push-action@v6
        with:
          context: .
          file: src/mssql/Dockerfile
          labels: |
            ${{ steps.meta.outputs.labels }}
            org.opencontainers.image.authors=sam@escd.dev
            org.opencontainers.image.title=dotnet-mssql-sdk
            org.opencontainers.image.vendor=Escape Developers, LLC
          push: true
          build-args: |
            DOTNET_VERSION=${{ matrix.dotnet_version }}
            SQL_VERSION=${{ matrix.sql_version }}
          tags: ghcr.io/escd/dotnet-mssql-sdk:${{ matrix.dotnet_version }}-${{ matrix.sql_version }}

      - name: publish attestation
        uses: actions/attest-build-provenance@v2
        id: attest
        if: ${{ !github.event.repository.private }}
        with:
          subject-name: ghcr.io/escd/dotnet-mssql-sdk
          subject-digest: ${{ steps.publish.outputs.digest }}
          push-to-registry: true

  wasm-sdk:
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet_version: ["8.0", "9.0", "10.0"]

    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: login ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: setup docker
        uses: docker/setup-buildx-action@v3

      - name: extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/escd/dotnet-wasm-sdk
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: publish image
        id: publish
        uses: docker/build-push-action@v6
        with:
          context: .
          file: src/wasm/Dockerfile
          labels: |
            ${{ steps.meta.outputs.labels }}
            org.opencontainers.image.authors=sam@escd.dev
            org.opencontainers.image.title=dotnet-wasm-sdk
            org.opencontainers.image.vendor=Escape Developers, LLC
          push: true
          build-args: |
            DOTNET_VERSION=${{ matrix.dotnet_version }}
          tags: ghcr.io/escd/dotnet-wasm-sdk:${{ matrix.dotnet_version }}

      - name: publish attestation
        uses: actions/attest-build-provenance@v3
        id: attest
        if: ${{ !github.event.repository.private }}
        with:
          subject-name: ghcr.io/escd/dotnet-wasm-sdk
          subject-digest: ${{ steps.publish.outputs.digest }}
          push-to-registry: true
